# app2.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: charttest1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/IfeanyiSam/J_E_C_TASK'
    path: demo-dev/HelmCharts/ChartTest1
    targetRevision: HEAD
    helm:
      releaseName: charttest1
      valueFiles:
      - values_dev.yaml 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: development
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true